import Foundation
import Testing

@Test func payloadUsesOnlyVersionedCodexDOMAnchors() throws {
    let testFile = URL(fileURLWithPath: #filePath)
    let repositoryRoot = testFile
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let payloadURL = repositoryRoot
        .appendingPathComponent("Sources/CodexModelRailInjector/Resources/model-rail.js")
    let payload = try String(contentsOf: payloadURL, encoding: .utf8)

    #expect(payload.contains("data-codex-intelligence-trigger"))
    #expect(payload.contains("data-composer-navigation-target=\"reasoning\""))
    #expect(payload.contains("data-radix-menu-content"))
    #expect(payload.contains("data-reasoning-slider"))
    #expect(payload.contains("data-composer-overlay-floating-ui"))
    #expect(payload.contains("data-list-navigation-item"))
    #expect(payload.contains("isSecondarySurface"))
    #expect(payload.contains("isSecondaryPickerOpen"))
    #expect(payload.contains("querySelectorAll(SECONDARY_ITEM_SELECTOR).length >= 2"))
    #expect(payload.contains("if (isSecondaryPickerOpen()) return null"))
    #expect(payload.contains("prototype: false"))
    #expect(payload.contains("visualPending: false"))
    #expect(payload.contains("localOnly: true"))
    #expect(payload.contains("design: \"preview-2d\""))
    #expect(payload.contains("document.body.append(host)"))
    #expect(payload.contains("computePlacement"))
    #expect(payload.contains("hidden-no-fit"))
    #expect(payload.contains("!overlaps(rect, anchorRect)"))
    #expect(payload.contains("ResizeObserver"))
    #expect(payload.contains("attachShadow"))
    #expect(payload.contains("--popover: rgb(44, 44, 44)"))
    #expect(payload.contains("width: 280px"))
    #expect(payload.contains("height: 151px"))
    #expect(payload.contains("transform: scale(0.5)"))
    #expect(payload.contains("transform-origin: top left"))
    #expect(payload.contains("const STAGE_WIDTH = 388"))
    #expect(payload.contains("const RIGHT_PADDING = 34"))
    #expect(payload.contains("--stage-w: 388px"))
    #expect(payload.contains("--text-scale: 1.2"))
    #expect(payload.contains("padding: 38px 32px 22px"))
    #expect(payload.contains("column-gap: 0"))
    #expect(payload.contains("top: -22px"))
    #expect(payload.contains("padding-left: 90px"))
    #expect(payload.contains("name: \"Sol\""))
    #expect(payload.contains("name: \"Terra\""))
    #expect(payload.contains("name: \"Luna\""))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5, 6]"))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5]"))
    #expect(payload.contains("modelElement.textContent = \"Other\""))
    #expect(payload.contains("data-selector-has-selection"))
    #expect(payload.contains("setPointerCapture"))
    #expect(payload.contains("state.fastMode = !state.fastMode"))
    #expect(payload.contains("event.key.startsWith(\"Arrow\")"))
    #expect(payload.contains("handleWindowBlur"))
    #expect(payload.contains("event.key === \"Escape\""))
    #expect(payload.contains("MutationObserver"))
    #expect(!payload.contains("fetch("))
    #expect(!payload.contains("XMLHttpRequest"))
    #expect(!payload.contains("localStorage"))
    #expect(!payload.contains("sessionStorage"))
    #expect(!payload.contains("indexedDB"))
    #expect(!payload.contains("document.cookie"))
}
