import Foundation
import Testing

@Test func payloadUsesOnlyVersionedCodexDOMAnchors() throws {
    let testFile = URL(fileURLWithPath: #filePath)
    let repositoryRoot = testFile
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let payloadURL = repositoryRoot
        .appendingPathComponent("Sources/CodexModelRailInjector/Resources/model-rail.js")
    let payload = try String(contentsOf: payloadURL, encoding: .utf8)

    #expect(payload.contains("data-codex-intelligence-trigger"))
    #expect(payload.contains("data-composer-navigation-target=\"reasoning\""))
    #expect(payload.contains("data-radix-menu-content"))
    #expect(payload.contains("data-reasoning-slider"))
    #expect(payload.contains("data-composer-overlay-floating-ui"))
    #expect(payload.contains("data-list-navigation-item"))
    #expect(payload.contains("data-model-picker-model-row"))
    #expect(payload.contains("isSecondarySurface"))
    #expect(payload.contains("findModelPickerObstacleSurfaces"))
    #expect(payload.contains("for (const row of document.querySelectorAll(MODEL_ROW_SELECTOR))"))
    #expect(payload.contains("const surfaces = new Set();"))
    #expect(payload.contains("secondaryExcluded: false"))
    #expect(payload.contains("secondaryAvoided: true"))
    #expect(payload.contains("...topCandidates"))
    #expect(payload.contains("placementVariant: \"center\""))
    #expect(payload.contains("clearsObstacles"))
    #expect(payload.contains("data-secondary-obstacle-count"))
    #expect(payload.contains("prototype: false"))
    #expect(payload.contains("visualPending: false"))
    #expect(payload.contains("localOnly: false"))
    #expect(payload.contains("switchMode: \"thread-settings-update\""))
    #expect(payload.contains("data-above-composer-conversation-id"))
    #expect(payload.contains("window.electronBridge"))
    #expect(payload.contains("sendMessageFromView"))
    #expect(payload.contains("type: \"mcp-request\""))
    #expect(payload.contains("\"model/list\""))
    #expect(payload.contains("\"thread/settings/update\""))
    #expect(payload.contains("thread/settings/updated"))
    #expect(payload.contains("serviceTier: selection.fastMode ? catalogEntry.fastTierID : null"))
    #expect(payload.contains("String(tier?.name || \"\").toLocaleLowerCase() === \"fast\""))
    #expect(payload.contains("createSettingsWaiter"))
    #expect(payload.contains("applySelection(previousConfirmed)"))
    #expect(payload.contains("commitCurrentSelection"))
    #expect(payload.contains("design: \"preview-2d\""))
    #expect(payload.contains("document.body.append(host)"))
    #expect(payload.contains("computePlacement"))
    #expect(payload.contains("hidden-no-fit"))
    #expect(payload.contains("!overlaps(rect, anchorRect)"))
    #expect(payload.contains("ResizeObserver"))
    #expect(payload.contains("attachShadow"))
    #expect(payload.contains("--popover: rgb(44, 44, 44)"))
    #expect(payload.contains("width: 289.75px"))
    #expect(payload.contains("height: 134.75px"))
    #expect(payload.contains("transform: scale(0.5)"))
    #expect(payload.contains("transform-origin: top left"))
    #expect(payload.contains("top: -4px"))
    #expect(payload.contains("const STAGE_WIDTH = 388"))
    #expect(payload.contains("const RIGHT_PADDING = 34"))
    #expect(payload.contains("--stage-w: 388px"))
    #expect(payload.contains("--text-scale: 1.2"))
    #expect(payload.contains("padding: 40px 26px 17.5px"))
    #expect(payload.contains("column-gap: 0"))
    #expect(payload.contains("top: -22px"))
    #expect(payload.contains("margin-top: 34px"))
    #expect(payload.contains("padding-top: 34px"))
    #expect(payload.contains("padding-left: 90px"))
    #expect(payload.contains(".current-selection {\n          display: none;"))
    #expect(payload.contains("effort-endpoint faster"))
    #expect(payload.contains("effort-endpoint smarter"))
    #expect(payload.contains("className = \"effort-model\""))
    #expect(payload.contains("className = \"effort-fast\""))
    #expect(payload.contains("--model-text-dark"))
    #expect(payload.contains("name: \"Sol\""))
    #expect(payload.contains("name: \"Terra\""))
    #expect(payload.contains("name: \"Luna\""))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5, 6]"))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5]"))
    #expect(payload.contains("modelElement.textContent = \"Other\""))
    #expect(payload.contains("class=\"other-label\""))
    #expect(payload.contains(".other-label.active { opacity: 1; }"))
    #expect(payload.contains("otherElement?.classList.toggle(\"active\", !selected)"))
    #expect(payload.contains("color: #8e8e93"))
    #expect(payload.contains("data-selector-has-selection"))
    #expect(payload.contains("Math.max(ROW_HEIGHT, width - START_INSET)"))
    #expect(payload.contains("setPointerCapture"))
    #expect(payload.contains("state.fastMode = !state.fastMode"))
    #expect(payload.contains("event.key.startsWith(\"Arrow\")"))
    #expect(payload.contains("event.code === \"Space\""))
    #expect(payload.contains("scheduleSelectionCommit"))
    #expect(payload.contains("data-keyboard-navigation"))
    #expect(payload.contains("data-open-state"))
    #expect(payload.contains("translateY(6px) scale(0.98)"))
    #expect(payload.contains("revealDetachedPopover"))
    #expect(payload.contains("POPOVER_ANIMATION_MS"))
    #expect(payload.contains("if (!wasOpen) host.style.transition = \"none\""))
    #expect(payload.contains("void host.offsetWidth"))
    #expect(payload.contains("handleWindowBlur"))
    #expect(payload.contains("event.key === \"Escape\""))
    #expect(payload.contains("MutationObserver"))
    #expect(!payload.contains("fetch("))
    #expect(!payload.contains("XMLHttpRequest"))
    #expect(!payload.contains("localStorage"))
    #expect(!payload.contains("sessionStorage"))
    #expect(!payload.contains("indexedDB"))
    #expect(!payload.contains("document.cookie"))
    #expect(!payload.contains("gpt-5.6-sol"))
    #expect(!payload.contains("gpt-5.6-terra"))
    #expect(!payload.contains("gpt-5.6-luna"))
}
