import Foundation
import Testing

@Test func payloadUsesOnlyVersionedCodexDOMAnchors() throws {
    let testFile = URL(fileURLWithPath: #filePath)
    let repositoryRoot = testFile
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let payloadURL = repositoryRoot
        .appendingPathComponent("Sources/CopickerCLI/Resources/model-rail.js")
    let payload = try String(contentsOf: payloadURL, encoding: .utf8)

    #expect(payload.contains("data-codex-intelligence-trigger"))
    #expect(payload.contains("data-composer-navigation-target=\"reasoning\""))
    #expect(payload.contains("data-radix-menu-content"))
    #expect(payload.contains("data-reasoning-slider"))
    #expect(payload.contains("data-composer-overlay-floating-ui"))
    #expect(payload.contains("const SECONDARY_ITEM_SELECTOR = '[data-list-navigation-item=\"true\"]'"))
    #expect(payload.contains("const OFFICIAL_MENU_ITEM_SELECTOR ="))
    #expect(payload.contains("[role=\"menuitem\"]"))
    #expect(payload.contains("[role=\"menuitem\"][aria-haspopup=\"menu\"][aria-controls]"))
    #expect(payload.contains("[role=\"menuitem\"]:not([aria-haspopup])"))
    #expect(!payload.contains("button[data-list-navigation-item]"))
    #expect(payload.contains("data-model-picker-model-row"))
    #expect(payload.contains("isSecondarySurface"))
    #expect(payload.contains("findSecondaryMenuObstacleSurfaces"))
    #expect(payload.contains("for (const row of document.querySelectorAll(MODEL_ROW_SELECTOR))"))
    #expect(payload.contains("new Set(document.querySelectorAll(PRIMARY_SURFACE_SELECTOR))"))
    #expect(payload.contains("const composerInputOverlay"))
    #expect(payload.contains("!composerInputOverlay"))
    #expect(payload.contains("secondaryExcluded: false"))
    #expect(payload.contains("secondaryAvoided: true"))
    #expect(payload.contains("...proposedTopCandidates"))
    #expect(payload.contains("placementVariant: \"center\""))
    #expect(payload.contains("placementIsValid"))
    #expect(payload.contains("data-secondary-obstacle-count"))
    #expect(payload.contains("prototype: false"))
    #expect(payload.contains("visualPending: false"))
    #expect(payload.contains("localOnly: false"))
    #expect(payload.contains("switchMode: \"thread-settings-update\""))
    #expect(payload.contains("noThreadSwitchMode: \"official-control-proxy\""))
    #expect(payload.contains("data-no-thread-switch-mode"))
    #expect(payload.contains("data-above-composer-conversation-id"))
    #expect(payload.contains("window.electronBridge"))
    #expect(payload.contains("sendMessageFromView"))
    #expect(payload.contains("type: \"mcp-request\""))
    #expect(payload.contains("\"model/list\""))
    #expect(payload.contains("\"thread/settings/update\""))
    #expect(payload.contains("\"thread/loaded/list\""))
    #expect(payload.contains("\"mcpServer/tool/call\""))
    #expect(payload.contains("thread/settings/updated"))
    #expect(payload.contains("serviceTier: selection.fastMode ? catalogEntry.fastTierID : null"))
    #expect(payload.contains("[\"priority\", \"fast\"].includes("))
    #expect(payload.contains(
        "String(tier?.name || \"\").trim().toLocaleLowerCase() === \"fast\""
    ))
    #expect(payload.contains("createSettingsWaiter"))
    #expect(payload.contains("performNoThreadSelectionCommit"))
    #expect(payload.contains("performOfficialControlProxy"))
    #expect(payload.contains("selectOfficialModel"))
    #expect(payload.contains("selectOfficialEffort"))
    #expect(payload.contains("selectOfficialFastMode"))
    #expect(payload.contains("ensureOfficialAdvancedRows"))
    #expect(payload.contains("restoreOfficialPickerView"))
    #expect(payload.contains("context.expandedAdvanced = true"))
    #expect(payload.contains("officialControlIsUsable"))
    #expect(payload.contains("supportedEffortOrder"))
    #expect(payload.contains("fastTierOptionIndex"))
    #expect(payload.contains("candidate.querySelector(OFFICIAL_SELECTED_EFFORT_SELECTOR)"))
    #expect(payload.contains("rows.layoutKind === \"power-submenus\""))
    #expect(payload.contains("hasExactThreeFlyoutLayout"))
    #expect(payload.contains("officialItemsExcludingDaybreakProgram"))
    #expect(payload.contains("structuralItems.length === 3"))
    #expect(payload.contains("officialAdvancedToggleTarget"))
    #expect(payload.contains("if (controls.length !== 1) return null"))
    #expect(payload.contains("officialSpeedConfirmationSource"))
    #expect(payload.contains("officialServiceTierTransitionPlan"))
    #expect(payload.contains("officialServiceTierFastState"))
    #expect(payload.contains("officialExactLabelMatch"))
    #expect(payload.contains("officialElementMatchesModelLabels"))
    #expect(payload.contains("normalizedOfficialModelCatalog"))
    #expect(payload.contains("normalizedSelectableModelCatalog"))
    #expect(payload.contains("includeHidden: true"))
    #expect(payload.contains("candidate?.hidden !== true"))
    #expect(payload.contains("async function loadOfficialModelCatalog()"))
    #expect(payload.contains("result?.nextCursor ?? result?.next_cursor ?? null"))
    #expect(!payload.contains("officialTriggerShowsOption"))
    #expect(payload.contains("officialSelectedLeafIndex"))
    #expect(payload.contains("officialLeafSemanticSignature"))
    #expect(payload.contains("serviceTierLeafSignature"))
    #expect(payload.contains("const OFFICIAL_CHECK_ICON_SELECTOR = 'svg[width=\"17\"][height=\"17\"]'"))
    #expect(payload.contains("if (toggles.length === 0)"))
    #expect(payload.contains("clickOfficialControl(fallbackTrigger)"))
    #expect(payload.contains("const targetIndex = enabled ? catalogEntry?.fastTierOptionIndex : 0"))
    #expect(!payload.contains("catalog-standard-only"))
    #expect(payload.contains("selected-model-leaf"))
    #expect(payload.contains("resolveOfficialModelTarget"))
    #expect(payload.contains("captureOfficialSelectionBaseline"))
    #expect(payload.contains("readOfficialSelectionBaselineSnapshot"))
    #expect(payload.contains("restoreOfficialSelectionBaseline"))
    #expect(payload.contains("selectOfficialServiceTierIndex"))
    #expect(payload.contains("coPickerSelectionFromOfficialBaseline"))
    #expect(payload.contains("resolveOfficialEffortTarget"))
    #expect(payload.contains("DAYBREAK_PROGRAM_CONTROL_SELECTOR"))
    #expect(payload.contains("officialDaybreakProgramState"))
    #expect(payload.contains("daybreakProgramAllowsBaseConfirmation"))
    #expect(payload.contains("officialProxyContextTrigger"))
    #expect(payload.contains("assertOfficialProxyContext"))
    #expect(!payload.contains("config/batchWrite"))
    #expect(!payload.contains("clearPrewarmedThreads"))
    #expect(payload.contains("railBaseline || previousConfirmed ||"))
    #expect(payload.contains("options?.railBaseline || state.confirmedSelection ||"))
    #expect(payload.contains("commitCurrentSelection"))
    #expect(payload.contains("officialSelectionMutationGeneration"))
    #expect(payload.contains("state.confirmedThreadID === threadID"))
    #expect(payload.contains("reconcileSettingsNotification"))
    #expect(payload.contains("settings: settings ? { ...settings } : null"))
    #expect(payload.contains("data-above-composer-conversation-id"))
    #expect(payload.contains("design: \"preview-2d\""))
    #expect(payload.contains("document.body.append(host)"))
    #expect(payload.contains("computePlacement"))
    #expect(payload.contains("hidden-no-fit"))
    #expect(payload.contains("!overlaps(rect, anchorRect)"))
    #expect(payload.contains("ResizeObserver"))
    #expect(payload.contains("attachShadow"))
    #expect(payload.contains("--popover: rgb(44, 44, 44)"))
    #expect(payload.contains("const HOST_WIDTH = POPOVER_INNER_WIDTH * 0.5"))
    #expect(payload.contains("const HOST_HEIGHT = 134.75 + Math.max(0, ROWS.length - 3) * 32"))
    #expect(payload.contains("transform: scale(0.5)"))
    #expect(payload.contains("transform-origin: top left"))
    #expect(payload.contains("top: -4px"))
    #expect(payload.contains("const STAGE_WIDTH = 388"))
    #expect(payload.contains("const RIGHT_PADDING = 34"))
    #expect(payload.contains("--stage-w: 388px"))
    #expect(payload.contains("--text-scale: 1.2"))
    #expect(payload.contains("padding: 40px 26px 17.5px"))
    #expect(payload.contains("column-gap: 0"))
    #expect(payload.contains("top: -22px"))
    #expect(payload.contains("margin-top: 34px"))
    #expect(payload.contains("padding-top: 34px"))
    #expect(payload.contains("padding-left: 90px"))
    #expect(payload.contains(".current-selection {\n          display: none;"))
    #expect(payload.contains("effort-endpoint faster"))
    #expect(payload.contains("effort-endpoint smarter"))
    #expect(payload.contains("className = \"effort-model\""))
    #expect(payload.contains("className = \"effort-fast\""))
    #expect(payload.contains("--model-text-dark"))
    #expect(payload.contains("name: \"Sol\""))
    #expect(payload.contains("name: \"Terra\""))
    #expect(payload.contains("name: \"Luna\""))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5, 6]"))
    #expect(payload.contains("dots: [1, 2, 3, 4, 5]"))
    #expect(payload.contains("renderInactiveStatus(otherElement, recognizedRow, recognizedEffort)"))
    #expect(payload.contains("class=\"other-label\""))
    #expect(payload.contains(".other-label.active { opacity: 1; }"))
    #expect(payload.contains("otherElement?.classList.toggle(\"active\", !selected)"))
    #expect(payload.contains("--secondary-text: #8e8e93"))
    #expect(payload.contains("data-selector-has-selection"))
    #expect(payload.contains("Math.max(ROW_HEIGHT, width - START_INSET)"))
    #expect(payload.contains("setPointerCapture"))
    #expect(payload.contains("state.fastMode = !state.fastMode"))
    #expect(payload.contains("event.key.startsWith(\"Arrow\")"))
    #expect(payload.contains("event.code === \"Space\""))
    #expect(payload.contains("scheduleSelectionCommit"))
    #expect(payload.contains("data-keyboard-navigation"))
    #expect(payload.contains("data-open-state"))
    #expect(payload.contains("translateY(6px) scale(0.98)"))
    #expect(payload.contains("revealDetachedPopover"))
    #expect(payload.contains("POPOVER_ANIMATION_MS"))
    #expect(payload.contains("if (!wasOpen) host.style.transition = \"none\""))
    #expect(payload.contains("void host.offsetWidth"))
    #expect(payload.contains("handleWindowBlur"))
    #expect(payload.contains("event.key === \"Escape\""))
    #expect(payload.contains("MutationObserver"))
    #expect(payload.contains("__COPICKER_SETTINGS_INTEGRATION__"))
    #expect(payload.contains("copicker-settings-nav-button"))
    #expect(payload.contains("button[data-settings-panel-slug=\"browser-use\"]"))
    #expect(payload.contains("button[data-settings-panel-slug=\"plugins-settings\"]"))
    #expect(payload.contains("nativeSettingsButton"))
    #expect(payload.contains("fallbackDocument.querySelectorAll(\"script\")"))
    #expect(payload.contains("frame.setAttribute(\"sandbox\", \"allow-same-origin\")"))
    #expect(!payload.contains("frame.setAttribute(\"sandbox\", \"allow-scripts\")"))
    #expect(payload.contains("const VERSION = \"0.12.14\""))
    #expect(payload.contains("SETTINGS_FRAME_STYLE_VARIABLES"))
    #expect(payload.contains("syncSettingsFrameStyleVariables"))
    #expect(payload.contains("nativeSettingsScrollViewport"))
    #expect(payload.contains("rect.width >= containerRect.width * 0.85"))
    #expect(!payload.contains("\"--text-2xl--line-height\""))
    #expect(payload.contains("\"--color-chart-blue\""))
    #expect(payload.contains("\"--copicker-host-border-default\""))
    #expect(payload.contains("installSettingsFrameController"))
    #expect(payload.contains("normalizedSettingsSnapshot"))
    #expect(payload.contains("copicker_settings_apply"))
    #expect(payload.contains("normalizedSettingsApplyResult"))
    #expect(payload.contains("SETTINGS_APPLY_REQUEST_TIMEOUT_MS"))
    #expect(payload.contains("当前窗口已更新，无需重启"))
    #expect(payload.contains("server: SETTINGS_SERVER_NAME"))
    #expect(payload.contains("tool: name"))
    #expect(payload.contains("const CONFIG = normalizeConfig(window.__COPICKER_CONFIG__)"))
    #expect(payload.contains("previous?.configSignature === CONFIG_SIGNATURE"))
    #expect(payload.contains("id: \"gpt-5.5\""))
    #expect(payload.contains("name: \"Daybreak\""))
    #expect(payload.contains("catalogDisplayName: \"Daybreak Blue\""))
    #expect(payload.contains("id: \"gpt-5.3-codex-spark\""))
    #expect(payload.contains("supportsFast: false"))
    #expect(payload.contains("!ROWS[state.currentRow].supportsFast"))
    #expect(payload.contains("officialRowForElement(trigger) ||"))
    #expect(payload.contains("officialRowFromCurrentModelControls(state.primarySurface)"))
    #expect(payload.contains(".label.daybreak { color: var(--daybreak-label); }"))
    #expect(payload.contains("justify-content: flex-end"))
    #expect(payload.contains("dots: [1, 2, 3, 4]"))
    #expect(payload.contains("if (matches.length !== 1) return null"))
    #expect(payload.contains("requiredEfforts.some((effort) => !model.supportedEfforts.has(effort))"))
    #expect(payload.contains("data-preferred-placement"))
    #expect(payload.contains("data-placement-latched"))
    #expect(payload.contains("state.latchedPlacement"))
    #expect(payload.contains("state.pointerInsidePopover"))
    #expect(payload.contains("PLACEMENT_RETURN_DELAY_MS"))
    #expect(payload.contains("placementVariant: \"obstacle-left\""))
    #expect(payload.contains("placementVariant: \"raised\""))
    #expect(payload.contains("...obstacleRects.map((obstacleRect) => obstacleRect.top)"))
    #expect(payload.contains("CONFIG.preferredPlacement !== \"top\""))
    #expect(payload.contains("data-appearance-resolved"))
    #expect(payload.contains("integration.frame?.contentDocument?.documentElement"))
    #expect(payload.contains("frameRoot.style.colorScheme = appearance"))
    #expect(payload.contains("main.setAttribute(\"aria-busy\", String(loading))"))
    #expect(payload.contains("--popover: rgb(255, 255, 255)"))
    #expect(payload.contains("background: rgb(255, 255, 255)"))
    #expect(payload.contains("CONFIG.appearance === \"system\""))
    #expect(!payload.contains("fetch("))
    #expect(!payload.contains("XMLHttpRequest"))
    #expect(!payload.contains("localStorage"))
    #expect(!payload.contains("sessionStorage"))
    #expect(!payload.contains("indexedDB"))
    #expect(!payload.contains("document.cookie"))
    #expect(!payload.contains("gpt-5.6-sol"))
    #expect(!payload.contains("gpt-5.6-terra"))
    #expect(!payload.contains("gpt-5.6-luna"))
}
